apiVersion: apps/v1
kind: Deployment
metadata:
  name: tooljet
spec:
  selector:
    matchLabels:
      app: tooljet
  template:
    metadata:
      labels:
        app: tooljet
    spec:
      containers:
        - name: tooljet
          image: "tooljet/tooljet-ce:{{ .Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
          args: ["npm", "run", "start:prod"]
          ports:
            - name: http
              containerPort: 3000
          resources:
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
          readinessProbe:
            httpGet:
              port: 3000
              path: /api/health
            successThreshold: 1
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 6
          env:
            - name: TOOLJET_HOST
              value: 'https://{{ index .Values.ingress.hosts 0 }}'
            - name: PG_HOST
              value: "{{ .Release.Name }}-postgresql"
            - name: PG_USER
              valueFrom:
                secretKeyRef:
                  name: {{ default "tooljet-server" .Values.existingSecret }}
                  key: pg_user
            - name: PG_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ default "tooljet-server" .Values.existingSecret }}
                  key: pg_password
            - name: PG_DB
              valueFrom:
                secretKeyRef:
                  name: {{ default "tooljet-server" .Values.existingSecret }}
                  key: pg_db
            - name: LOCKBOX_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ default "tooljet-server" .Values.existingSecret }}
                  key: lockbox_key
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: {{ default "tooljet-server" .Values.existingSecret }}
                  key: secret_key_base
            - name: DEPLOYMENT_PLATFORM
              value: "k8s:helm"
