{{- if .Values.hpa.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: tooljet
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tooljet
  minReplicas: {{ .Values.hpa.min }}
  maxReplicas: {{ .Values.hpa.max }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageValue: {{ .Values.hpa.threshhold.cpu }}
  - type: Resource
    resource:
      name: memory
      targetAverageValue: {{ .Values.hpa.threshhold.ram }}
{{- end }}
