{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.secret.name }}"
type: Opaque
data:
  pg_user: {{ .Values.secret.data.pg_user | b64enc | quote }}
  pg_password: {{ .Values.secret.data.pg_password | b64enc | quote }}
  pg_db: {{ .Values.secret.data.pg_db | b64enc | quote }}
  lockbox_key: {{ .Values.secret.data.lockbox_key | b64enc | quote }}
  secret_key_base: {{ .Values.secret.data.secret_key_base | b64enc | quote }}
{{- end }}
