apiVersion: v1
kind: Service
metadata:
  name: tooljet
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: http
  selector:
    app: tooljet
