apiVersion: v1
kind: Service
metadata:
  name: {{ include "vikunja.fullname" . }}-api
  labels:
    component: api
    {{- include "vikunja.labels" . | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    component: api
    {{- include "vikunja.selectorLabels" . | nindent 4 }}
