{{- if (and .Values.api.persistence.files.enabled (not .Values.api.persistence.files.existingClaim)) -}}
{{- $fullName := include "vikunja.fullname" . -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $fullName }}-api-files
  labels:
    component: api
    {{- include "vikunja.labels" . | nindent 4 }}
spec:
  resources:
    requests:
      storage: {{ .Values.api.persistence.files.size }}
  volumeMode: Filesystem
  storageClassName: {{ .Values.api.persistence.files.storageClassName }}
  accessModes:
    - ReadWriteOnce
{{- end }}
