apiVersion: v1
kind: Service
metadata:
  name: {{ include "vikunja.fullname" . }}-frontend
  labels:
    component: frontend
    {{- include "vikunja.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    component: frontend
    {{- include "vikunja.selectorLabels" . | nindent 4 }}
