# Default values for akaunting.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: akaunting/akaunting
  pullPolicy: IfNotPresent
  tag: "3.0.6-v"

persistence:
  enabled: true
  existingClaim: ""
  storageClass: ""
  accessModes:
    - ReadWriteOnce
  size: 10Gi

env:
  APP_URL: "https://akaunting.example.com"
  LOCALE: de-DE
  DB_CONNECTION: mysql
  DB_HOST: ""
  DB_PORT: ""
  DB_NAME: akaunting
  DB_USERNAME: akaunting
  DB_PASSWORD:
    secretKeyRef:
      name: akaunting-postgres
      key: password
  DB_PREFIX: aka_
  COMPANY_NAME: My Corp
  COMPANY_EMAIL: my@corp.com
  ADMIN_EMAIL:
    secretKeyRef:
      name: akaunting-admin
      key: email
  ADMIN_PASSWORD:
    secretKeyRef:
      name: akaunting-admin
      key: password

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: akaunting.example.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

#
# Dependencies
#
redis:
  architecture: standalone
  master:
    count: 1
    kind: Deployment
    persistence:
      enabled: true
      existingClaim: ""
      storageClass: ""
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
    prometheusRule:
      enabled: true
  volumePermissions:
    enabled: true

mariadb:
  architecture: standalone
  auth:
    username: akaunting
    database: akaunting
    existingSecret: akaunting-db
  primary:
    persistence:
      enabled: true
      size: 8Gi
      storageClass: ""
      existingClaim: ""
  volumePermissions:
    enabled: true
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
    prometheusRule:
      enabled: true
