apiVersion: v2
name: vikunja
description: A Helm chart for Kubernetes
type: application
version: 0.0.1
appVersion: "0.18.2"
dependencies:
  - condition: postgresql.enabled
    name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 11.1.*
  - condition: redis.enabled
    name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 16.8.*
