apiVersion: v2
name: admidio
description: Admidio
type: application
version: 0.0.3
appVersion: "4.2.14"
dependencies:
- name: mariadb
  version: "11.3.1"
  repository: https://charts.bitnami.com/bitnami
  condition: mariadb.enabled
