service:
  type: ClusterIP

ingress:
  enabled: false
  tls: []
  hosts: []
  paths: []


resources:
  requests:
    memory: 4Gi
    cpu: 2
  limits:
    memory: 8Gi
    cpu: 4

extraEnv: []

hpa:
  enabled: false
  min: 1
  max: 1
  threshhold:
    cpu: 0.75
    ram: 768Mi
existingSecret: tooljet
secret:
  data:
    pg_user: "postgresql"
    pg_password: "postgresql"
    pg_db: "tooljet"
    lockbox_key: "0123456789ABCDEF"
    secret_key_base: "0123456789ABCDEF"

postgresql:
  enabled: true
  postgresqlExtendedConf:
    maxConnections: 1024
  replication:
    enabled: false
  auth:
    # postgresPassword: "postgres"
    username: "postgresql"
    password: "postgresql"
  primary:
    persistence:
      enabled: true
      size: 8Gi
      storageClass: ""
